### ISSUE TITLE
Sozialstatus

### ISSUE THREAD

**Issue by Scarjit** [svrin/dsa5gen#1]
Der Sozialstatus "Sklave" hat hat in Klammern "1 xundefined" stehen.
(Ich habe als Kultur Tulamidenlande gewählt)

Mfg

Scarjit

**Comment by svrin** [comment]
Danke für den Hinweis,

da im finalen Regelwerk der Sozialstatus etwas geändert wurde, fixe ich das sobald ich die Kulturen angepasst habe.

**Comment by svrin** [comment]
Hi,

ich habe jetzt die Kulturen nach dem neuen Regelwerk angepasst (Nur noch Professionen und Druckbogen to go!). Für den Sozialstatus sind jetzt nur noch die drei Möglichkeiten Adel/Frei/Unfrei wählbar. Falls du irgendwelche weiteren Bugs siehst, gerne melden.

~lg
